### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by pierrre** [globalsign/mgo#288]
mgo version: `r2018.06.15`

### What version of Go are you using (`go version`)?
```
1.11.1
```

### What operating system and processor architecture are you using (`go env`)?
```
linux amd64
```

### What did you do?

My application crashed with this error:
```
fatal error: concurrent map read and map write

goroutine 343063 [running]:
runtime.throw(0xb02504, 0x21)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/panic.go:608 +0x72 fp=0xc0005ad1f8 sp=0xc0005ad1c8 pc=0x42db32
runtime.mapaccess2(0xa2aec0, 0xc00042fb90, 0xc000230680, 0xc00123b600, 0xc0005ad290)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/map.go:453 +0x223 fp=0xc0005ad240 sp=0xc0005ad1f8 pc=0x40f3e3
reflect.mapaccess(0xa2aec0, 0xc00042fb90, 0xc000230680, 0xafb06a)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/map.go:1249 +0x3f fp=0xc0005ad278 sp=0xc0005ad240 pc=0x41152f
reflect.Value.MapIndex(0xa2aec0, 0xc00042fb90, 0x15, 0x9ee9c0, 0xc000230680, 0x98, 0xa14b00, 0xc000230800, 0x94)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/reflect/value.go:1111 +0x11d fp=0xc0005ad2f8 sp=0xc0005ad278 pc=0x4b853d
github.com/org/project/vendor/github.com/globalsign/mgo/bson.(*encoder).addMap(0xc0005af040, 0xa2aec0, 0xc00042fb90, 0x15)
        /home/travis/gopath/src/github.com/org/project/vendor/github.com/globalsign/mgo/bson/encode.go:206 +0x189 fp=0xc0005ad3b8 sp=0xc0005ad2f8 pc=0x5a6a49
github.com/org/project/vendor/github.com/globalsign/mgo/bson.(*encoder).addDoc(0xc0005af040, 0xa2aec0, 0xc00042fb90, 0x15)
        /home/travis/gopath/src/github.com/org/project/vendor/github.com/globalsign/mgo/bson/encode.go:191 +0x329 fp=0xc0005ad490 sp=0xc0005ad3b8 pc=0x5a63b9
github.com/org/project/vendor/github.com/globalsign/mgo/bson.(*encoder).addElem(0xc0005af040, 0x9c0e2b, 0xa, 0xa2aec0, 0xc00042fb90, 0x15, 0x0)
        /home/travis/gopath/src/github.com/org/project/vendor/github.com/globalsign/mgo/bson/encode.go:462 +0x3cef fp=0xc0005ae120 sp=0xc0005ad490 pc=0x5ac1af
github.com/org/project/vendor/github.com/globalsign/mgo/bson.(*encoder).addElem(0xc0005af040, 0x9c0e2b, 0xa, 0xa14ba0, 0xc000422fa0, 0x194, 0x100)
        /home/travis/gopath/src/github.com/org/project/vendor/github.com/globalsign/mgo/bson/encode.go:373 +0x3f11 fp=0xc0005aedb0 sp=0xc0005ae120 pc=0x5ac3d1
github.com/org/project/vendor/github.com/globalsign/mgo/bson.(*encoder).addStruct(0xc0005af040, 0xad6140, 0xc000422f70, 0x199)
        /home/travis/gopath/src/github.com/org/project/vendor/github.com/globalsign/mgo/bson/encode.go:254 +0x281 fp=0xc0005aef38 sp=0xc0005aedb0 pc=0x5a6d51
github.com/org/project/vendor/github.com/globalsign/mgo/bson.(*encoder).addDoc(0xc0005af040, 0x9d0140, 0xc000422f70, 0x16)
        /home/travis/gopath/src/github.com/org/project/vendor/github.com/globalsign/mgo/bson/encode.go:193 +0x36c fp=0xc0005af010 sp=0xc0005aef38 pc=0x5a63fc
github.com/org/project/vendor/github.com/globalsign/mgo/bson.MarshalBuffer(0x9d0140, 0xc000422f70, 0xc0041c8000, 0x34, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/org/project/vendor/github.com/globalsign/mgo/bson/bson.go:584 +0x12b fp=0xc0005af068 sp=0xc0005af010 pc=0x59aadb
github.com/org/project/vendor/github.com/globalsign/mgo.addBSON(0xc0041c8000, 0x34, 0x200, 0x9d0140, 0xc000422f70, 0x20, 0xc000574550, 0xc0005af148, 0x42d121, 0xb5b030)
        /home/travis/gopath/src/github.com/org/project/vendor/github.com/globalsign/mgo/socket.go:726 +0xf7 fp=0xc0005af0c8 sp=0xc0005af068 pc=0x6c8727
github.com/org/project/vendor/github.com/globalsign/mgo.(*mongoSocket).Query(0xc000250480, 0xc0005af6b0, 0x1, 0x1, 0x0, 0x0)
        /home/travis/gopath/src/github.com/org/project/vendor/github.com/globalsign/mgo/socket.go:485 +0x169c fp=0xc0005af640 sp=0xc0005af0c8 pc=0x6c60ac
github.com/org/project/vendor/github.com/globalsign/mgo.(*Query).Iter(0xc007106240, 0x0)
        /home/travis/gopath/src/github.com/org/project/vendor/github.com/globalsign/mgo/session.go:4078 +0x304 fp=0xc0005af6d0 sp=0xc0005af640 pc=0x6b9ac4
```

### Can you reproduce the issue on the latest `development` branch?

I can't use this branch, because it doesn't support MongoDB < 3.0.
I'm using different MongoDB versions (2.6 to 3.6).

**Comment by pierrre** [comment]
I found the cause of the issue, it was in my code.

The projection value was cached, but several goroutines where updating it concurrently, which is a data race.

Sorry
